### ISSUE TITLE
Controller Area Network

### ISSUE THREAD

**Issue by reneherrero** [rust-embedded/linux-embedded-hal#47]
Here to inquire on the steps to get CAN support added:
* There's a [PR](https://github.com/rust-embedded/embedded-hal/pull/212) well underway to get CAN support added to the `embedded-hal` repo.
* I have an [implementation](https://github.com/reneherrero/candev) that still needs some polishing, but is working.

Is submitting a PR here that references my repo the way to go?

**Comment by ryankurte** [comment]
hey thanks for the issue! as you suggest the best thing to do is to open a work-in-progress PR here with, links to upstream blocking PRs and dependencies.

**Comment by reneherrero** [comment]
Ok, I'll do some more polishing and get this in motion.
