### ISSUE TITLE
Update dependencies to use nix >= 0.23 due to vulnerability

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/linux-embedded-hal#70]
See: https://rustsec.org/advisories/RUSTSEC-2021-0119.html

- https://github.com/rust-embedded/rust-i2cdev/pull/69
- https://github.com/rust-embedded/rust-spidev/pull/37
- https://github.com/rust-embedded/gpio-cdev/pull/67
- https://github.com/rust-embedded/rust-sysfs-gpio/pull/72
- https://github.com/milkey-mouse/openpty/pull/7 (dev-dependency, optional)
- TODO: linux-embedded-hal

**Comment by ryankurte** [comment]
all lgtm, though i can't see that the particular issue has any impact in our crates.

**Comment by eldruin** [comment]
Thanks! Indeed it does not seem so. However, anything that depends on it starts getting flagged by cargo-audit.
Since it is the first time this comes up, I figured we might as well update.

**Comment by posborne** [comment]
Thanks for picking this one up and running with it @eldruin
