### ISSUE TITLE
Feature request: Add Serial implementation

### ISSUE THREAD

**Issue by rnestler** [rust-embedded/linux-embedded-hal#8]
As far as I can tell there isn't yet a [serial](https://docs.rs/embedded-hal/0.2.1/embedded_hal/serial/index.html) implementation here, is it?
I think one could probably implement it with the help of the [serial](https://crates.io/crates/serial) crate.

**Comment by RandomInsano** [comment]
If we do, I might take a stab at some GPS driver / event system.

**Comment by rnestler** [comment]
I noticed that there exists https://github.com/thenewwazoo/serial-embedded-hal already, which implements the embedded-hal serial trait with the serial crate.

**Comment by rnestler** [comment]
This is resolved with #9.
