### ISSUE TITLE
Enable i2c as a feature?

### ISSUE THREAD

**Issue by zuckschwerdt** [rust-embedded/linux-embedded-hal#80]
The dependency on `i2cdev` for `i2c` is currently the only thing tying this to linux. I confirmed this crate to compile and work on unix with `i2c` removed.
Would it be an option to offer `i2c` as a (default enabled) feature?

**Comment by ryankurte** [comment]
seems reasonable to me! though it may be a breaking change for folks selecting `gpio` implementations at the moment, maybe both `spi` and `i2c` so we're consistent?

**Comment by zuckschwerdt** [comment]
True, adding an `i2c` feature would break `default-features = false` (for `gpio` selection) setups.
Alternative could be conditional compilation on `target_os`, it would just-work and not expose settings. But there might be users wondering where `i2c` is (on host != target).

**Comment by eldruin** [comment]
I would be fine with adding `spi` and `i2c` features. We can do so in the upcoming 0.4.0 release, since it is breaking anyway and this does not seem time-critical to me.
Have you tested SPI to work on non-linux platforms? also, which platform are you working with?

**Comment by zuckschwerdt** [comment]
Not time-critical at all, just ergonomics to me. I use modular hardware, missing components are expected. Building with inaccessible or missing hardware interfaces is fine for me. In my application it turns out to be less involved to just recognize a missing /dev/spidev, GPIO or serial at runtime then to stub out all the code.

**Comment by zuckschwerdt** [comment]
For anyone wanting to test this, there are branches for 0.3 and 0.4 to show the changes:
- https://github.com/zuckschwerdt/linux-embedded-hal/tree/feat-i2cspi03
- https://github.com/zuckschwerdt/linux-embedded-hal/tree/feat-i2cspi04

**Comment by eldruin** [comment]
Nice, would you create a PR with your feat-i2cspi04 branch?
