### ISSUE TITLE
serial-unix crate is unmaintained

### ISSUE THREAD

**Issue by samgoldman-bionautlabs** [rust-embedded/linux-embedded-hal#86]
We have noticed that this crate uses serial-unix which has not been maintained in 5 years: https://github.com/dcuddeback/serial-rs. 

Instead the maintained crate serialport (https://github.com/serialport/serialport-rs) could be used.

**Comment by qrasmont** [comment]
Hi,

This means `Serial::open` should become a wrapper around `serialport::TTYPort::open` instead of `serial_unix::TTYPort::open`.

Is it then ok to modify the `Serial::open` signature to match the arguments expected by `serialport::TTYPort::open` ? Or should the existing signature be preserved ?

**Comment by eldruin** [comment]
Keeping the signature is not a must. It would be nice to keep if possible, though, just because it is currently very straight-forward by simply providing a path.
We have a breaking release in the pipeline so if you are interested, now it would be a great time to have a go at it.

**Comment by qrasmont** [comment]
The main difference is that `serial-rs` would rely on termios to get the baud rate while  `serialport-rs` requires the user to provide it to be able to open the port.

So the signature could be maintained by using termios.
