### ISSUE TITLE
SPI implementation panics if read and write buffers in a transfer are not the same length

### ISSUE THREAD

**Issue by adamgreig** [rust-embedded/linux-embedded-hal#97]
In [embedded-hal SPI transfers](https://docs.rs/embedded-hal/1.0.0-rc.1/embedded_hal/spi/trait.SpiBus.html#tymethod.transfer), the read and write buffers may be different lengths:

> It is allowed for read and write to have different lengths, even zero length. The transfer runs for max(read.len(), write.len()) words. If read is shorter, incoming words after read has been filled will be discarded. If write is shorter, the value of words sent in MOSI after all write has been sent is implementation-defined, typically 0x00, 0xFF, or configurable.

In [spidev read_write](https://docs.rs/spidev/latest/spidev/spidevioctl/struct.spi_ioc_transfer.html#method.read_write), it is not:

> Note that the tx_buf and rx_buf must be the same length.

However currently we implement `transfer` by calling `read_write` directly:

https://github.com/rust-embedded/linux-embedded-hal/blob/86ab035c7060732fc9cdd1aee7faa1e554b3b4b8/src/spi.rs#L100

leading to panics when the buffer lengths differ. We should adjust the buffers passed to `read_write`, or split the transfer into a read_write and a write or something, to accommodate.

**Comment by eldruin** [comment]
Fixed in #98. Thank you!
